version: "3.9"

services:
  postgres:
    image: postgres
    container_name: quickie-washie-postgres
    hostname: postgres
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "quickie-washie"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

